config/routes.rb
Rails.application.routes.draw do

  #authenticated :user do
    root :to => "home#index"
  #end

  #root :to => redirect("/users/sign_in")

  resources :quizzes, only: [] do
    get "question"
    post "answer"
    get "result"
  end

	post '/home', to: 'home#quiz_session', :defaults => { :rank => '1' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/quizzes_controller.rb
include QuizHelper

class QuizzesController < ApplicationController

  before_action :setup_or_gather_quiz_session, :generate_timer, except: :result

  def question
   @quiz = Quiz.find(params[:quiz_id])
   @question = @qs.find_unanswered_question
  end

  def answer
    qa = QuestionAnswer.create(param_permits)
    qa.quiz_session = @qs
    qa.check_answer(qa)
    qa.save!

    # @nxt_quiz_id = get_next_quiz?

    # if @qs.is_done? && @nxt_quiz_id
    #   redirect_to quiz_question_path(params[:quiz_id])

    # elsif @qs.is_done?
    #   redirect_to quiz_result_path(params[:quiz_id])
    #   session.delete(:quiz_session_id)
    #   session.delete(:quiz_start_time)
    if @qs.is_done?
      redirect_to root_path
    else
      redirect_to quiz_question_path(params[:quiz_id])
    end
  end

  def result

  end

private
  def param_permits
    params.require(:question_answer).permit(:answer, :question_id)
  end

  def setup_or_gather_quiz_session
    if session[:quiz_session_id].blank?
      redirect_to root_path
    else
      @qs = QuizSession.find(session[:quiz_session_id])
    end
  end

	def generate_timer
		@maxTime = @qs.quiz.max_time
		#@hour = @minute = @second = @maxTime
		return true if @maxTime < 1

		if has_reach_max_time?(@qs)
			#reset_session
      # session.delete(:quiz_session_id)
      # session.delete(:quiz_start_time)
			# redirect_to quiz_result_path(params[:quiz_id]), alert: "Time's Up!" and return
      redirect_to root_path
		end

    @total_seconds = (Time.now - @qs.created_at)
    @max_seconds = @maxTime.minute.to_i

    @hours = (@total_seconds / (60 * 60))
    @minutes = ((@total_seconds / 60) % 60)
    @seconds = (@total_seconds % 60)

    @hours, @minutes, @seconds = [@hours, @minutes, @seconds].map{|t| t.to_i.to_s.rjust(2, "0") }

	end

end

app/views/quizzes/question.html.haml
.progressBar
  %div
#countdown-timer.pull-right{data: {max_seconds: @max_seconds}}
  - unless @total_seconds >= @max_seconds
    %span#timer-hour
      = @hours
    \:
    %span#timer-minute
      = @minutes
    \:
    %span#timer-second
      = @seconds
= form_tag quiz_answer_path, class: "form-horizontal" do
  %fieldset
    / Form Name
    %h3
      = @quiz.name
    / Multiple Radios
    .form-group
      %input{:name => "question_answer[question_id]", :type => "hidden", :value => @question.id}/
      %label.col-md-12.control-label.quiz{:for => "choices"}
        = @question.label.html_safe
      %br/
      %div.container= image_tag @question.image.try(:url, :medium)
      .col-md-10.choices
        - (1..6).reject{|x| @question.send("option#{x}").blank? }.each do |choice|
          .radio
            %label{:for => "choices-#{choice}"}
              %input{:id => "choices-#{choice}", :name => "question_answer[answer]", :required => "", :type => "radio", :value => choice}/
              = @question.send("option#{choice}").gsub(/\n/, "<br>").html_safe
    / Button
    .form-group
      %label.col-md-4.control-label.sr-only{:for => "next"}
      .col-md-4.choicesnext
        %input#next.btn.btn-primary{:name => "next", :type => "submit", :value => "Next"}/

app/views/quizzes/result.html.haml
.container-fluid
  %h1 Thank you!
  %hr/
  .container
    .row
      .col-md-8
        %p We have received your assessment test for your employment purpose. Your Employer will be in touch with you shortly.
        %p
          While waiting, you may check our corporate website for more information:
          %a{:href => "http://ingedata.net", :target => "_blank"} Ingedata.net