config/routes.rb
Rails.application.routes.draw do

  #authenticated :user do
    root :to => "home#index"
  #end

  #root :to => redirect("/users/sign_in")

  resources :quizzes, only: [] do
    get "question"
    post "answer"
    get "result"
  end

	post '/home', to: 'home#quiz_session', :defaults => { :rank => '1' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
include HomeHelper
include QuizHelper

class HomeController < ApplicationController
	before_action :authenticate_user!, only: [:index]

	def index
		@exams = Exam.all #@TO-DO: all should be replaced with .find_by(office_id: curent_user.office_id) upon office implementation
		@qs_id = session[:quiz_session_id]
		@exam_started = !@qs_id.blank? && !session[:exam_id].blank?
		@exam = @exams.first
		@quiz = @exam.quizzes.first
		if @exam_started
			@quizSession = QuizSession.find @qs_id
			if @quizSession.is_done? || has_reach_max_time?(@quizSession)
				@exam = @exams.find session[:exam_id]
				@quiz = @exam.get_next_quiz @quizSession.quiz
				quiz_session_destroy
			else
				redirect_to quiz_question_path(params[:quiz_id])
			end
			# result page redirection when quiz is blank
			redirect_to quiz_result_path(@quizSession.quiz.id) if @quiz.blank?
		elsif @exams.count > 1 && !@exam_started #@TO-DO: should be tested for multiple exams (change if needed)
			@quiz = nil
		end
		session.delete(:quiz_session_id) unless session[:quiz_session_id].blank?
	end

	def quiz_session
		@quizSession = QuizSession.create(quiz_session_params)
		@quizSession.user = current_user
		@quizSession.first_name = @quizSession.last_name = @quizSession.email = ""
		if @quizSession.save
			quiz_session_create @quizSession.id, @quizSession.created_at, params[:exam_id]
			redirect_to quiz_question_path(@quizSession.quiz_id)
		else
			@errors = @quizSession.errors if @quizSession.errors.any?
			redirect_to root_path, alert: @errors.to_a.join(", ").to_s
		end
	end

private
	def quiz_session_params
		params.permit(:first_name, :last_name, :email, :address, :phone_number, :quiz_id)
	end
end

app/helpers/home_helper.rb
module HomeHelper

  def quiz_session_create qs_id, qs_time, exam_id
    session[:quiz_session_id] = qs_id
    session[:quiz_start_time] = qs_time
    session[:exam_id] = exam_id
  end

  def quiz_session_destroy
    session.delete :quiz_session_id
    session.delete :quiz_start_time
    session.delete :exam_id
  end
end

app/views/home/_ranks.html.haml
= @quizzes = Quiz.where(rank: [3])

app/views/home/index.html.haml
- page_title = 'Introduction'
- submit_icon = 'glyphicon glyphicon-play'
- submit_text = 'Start'
- submit_tooltip = 'Start taking this Exam'
- if @exam_started
  - page_title = 'Continuation'
  - submit_icon = 'glyphicon glyphicon-fast-forward'
  - submit_text = 'Next'
  - submit_tooltip = 'Continue taking this Exam'
= form_tag home_path, class: 'form-horizontal' do
  %fieldset
    %legend.formtitle
      = page_title
    .form-group
      = label_tag :exam_id, nil, class: 'col-md-4 control-label sr-only'
      .col-md-offset-4.col-md-4
        %br/
        %h5.center
          - if @exams.count > 1 && !@exam_started
            = select_tag :exam_id, options_from_collection_for_select(@exams, :id, :name, :rank), class: 'form-control', title: 'Exam', 'data-toggle': 'tooltip', 'data-placement': 'left', required: true
          - else
            = @exam.name.titleize
          %h3.center
            = @quiz.name.titleize
            = hidden_field_tag :exam_id, @exam.id
        - unless @quiz.blank?
          = hidden_field_tag :quiz_id, @quiz.id
          .well.well-sm.center{ id: "quiz-info-#{@exam.id}" }
            %em= @quiz.instruction.gsub(/\n/, '<br>').html_safe
            - if @quiz.max_time > 0
              %br/
              Maximum Time: #{@quiz.max_time} minute/s
            - if @quiz.max_attempts > 0
              %br/
              Maximum Attempt: #{@quiz.max_attempts}
        - else
          - @exams.each do |exam|
            - quiz = exam.quizzes.first
            = hidden_field_tag :quiz_id, quiz.id
            .well.well-sm{ id: "quiz-info-#{exam.id}" }
              %em= quiz.instruction.gsub(/\n/, '<br>').html_safe
              - if quiz.max_time > 0
                %br/
                Maximum Time: #{quiz.max_time} minute/s
              - if quiz.max_attempts > 0
                %br/
                Maximum Attempt: #{quiz.max_attempts}
    .actions.form-group
      .col-md-offset-4.col-md-4.text-center
        = button_tag type: 'submit', class: 'btn btn-primary btn-lg', title: submit_tooltip, 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
          = submit_text
          %i{ class: "#{submit_icon}" }
/ = form_tag home_path, class: "form-horizontal" do
/   %fieldset
/     %legend.formtitle Select Quiz
/     .form-group
/       = label_tag :quiz_id, nil, class: "col-md-4 control-label sr-only"
/       .col-md-offset-4.col-md-4
/         = select_tag :quiz_id, options_from_collection_for_select(@quizzes, :id, :name), class: "form-control", title: "Quiz", "data-toggle": "tooltip", "data-placement": "left", required: true
/     .form-group
/       .col-md-offset-4.col-md-4
/         - @quizzes.each do |quiz|
/           .well.well-sm{:id => "quiz-info-#{quiz.id}"}
/             %em= quiz.instruction.gsub(/\n/, "<br>").html_safe
/             - if quiz.max_time > 0
/               %br>/
/               Maximum Time: #{quiz.max_time} minute/s
/             - if quiz.max_attempts > 0
/               %br>/
/               Maximum Attempt: #{quiz.max_attempts}
/     .actions.form-group
/       .col-md-offset-4.col-md-4.text-center
/         = submit_tag "Proceed to Quiz", class: "btn btn-primary", title: "Proceed to Quiz", "data-toggle": "tooltip", "data-placement": "bottom"